mutation schemaDelete(
  $filters: SchemaFiltersSingle
) {
  schemaDelete(
    filters: $filters
  ) {
    errors
    errorsFields {
      field
      message
    }
    node {
      __typename
      deletedAt
      descriptionI18n
      enableDescription
      enableEndAt
      enableFile
      enableImage
      enableLocation
      enablePrice
      enablePriceCompareAt
      enableStartAt
      enableThumbnail
      enableTitle
      fileId
      handle
      id
      insertedAt
      isLatest
      private
      publishedAt
      schemaId
      slug
      titleI18n
      updatedAt
      userId
      
    }
  }
}