mutation schemaMutation(
  $changes: SchemaInput,
  $filters: SchemaFiltersSingle
) {
  schemaMutation(
    changes: $changes,
    filters: $filters
  ) {
    errors
    errorsFields {
      field
      message
    }
    node {
      __typename
      internalId
      deletedAt
      description
      enableDescription
      enableEndAt
      enableFile
      enableImage
      enableLocation
      enablePrice
      enablePriceCompareAt
      enableStartAt
      enableThumbnail
      enableTitle
      fileId
      handle
      id
      insertedAt
      isLatest
      private
      publishedAt
      schemaId
      slug
      title
      updatedAt
      userId
      
    }
  }
}