query schemaPublishedCollection(
  $after: String,
  $before: String,
  $first: Int,
  $last: Int,
  $filters: SchemaFilters,
  $search: String
) {
  schemaPublishedCollection(
    after: $after,
    before: $before,
    first: $first,
    filters: $filters,
    last: $last,
    search: $search
  ) {
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    count
    countBefore
    edges {
      node {
        __typename
        internalId
        deletedAt
        descriptionI18n
        fileId
        handle
        id
        insertedAt
        isLatest
        private
        publishedAt
        masterSchemaId
        slug
        titleI18n
        updatedAt
        userId
      }
      cursor
    }
  }
}