query schemaSingle(
  $filters: SchemaFiltersSingle
) {
  schemaSingle(
    filters: $filters
  ) {
    __typename
    internalId
    deletedAt
    descriptionI18n
    fileId
    handle
    id
    insertedAt
    isLatest
    private
    publishedAtHuman
    slug
    titleI18n
    updatedAt
    userId
  }
}