query schemaSingle(
  $filters: SchemaFiltersSingle
) {
  schemaSingle(
    filters: $filters
  ) {
    __typename
    internalId
    deletedAt
    description
    fileId
    handle
    id
    insertedAt
    isLatest
    private
    publishedAt
    schemaId
    slug
    title
    updatedAt
    userId
    
  }
}