mutation schemaDelete(
  $filters: SchemaFiltersSingle
) {
  schemaDelete(
    filters: $filters
  ) {
    errors
    errorsFields {
      field
      message
    }
    node {
      __typename
      deletedAt
      description
      fileId
      handle
      id
      insertedAt
      isLatest
      private
      publishedAt
      schemaId
      slug
      title
      updatedAt
      userId
      
    }
  }
}