query fieldSingle(
  $filters: FieldFiltersSingle
) {
  fieldSingle(
    filters: $filters
  ) {
    __typename
    internalId
    deletedAt
    descriptionI18n
    fileId
    handle
    id
    imageId
    insertedAt
    isBody
    isDescription
    isImage
    isLocation
    isThumbnail
    isTime
    isTitle
    meta
    ordering
    placeholderI18n
    schemaId
    titleI18n
    type
    updatedAt
    userId
    validations
    
  }
}