mutation fieldOrderingMutation(
    $fields: [FieldUpdateInput]
) {
  fieldOrderingMutation(
    fields: $fields
  ) {
    errors
    errorsFields {
      field
      message
    }
    nodes {
      __typename
      id
      internalId
      ordering
    }
  }
}