query entrySingle(
  $filters: EntryFiltersSingle
) {
  entrySingle(
    filters: $filters
  ) {
    __typename
    internalId
    dataI18n
    descriptionI18n
    entryMasterId
    handle
    id
    insertedAt
    metaI18n
    publishedAt
    schemaId
    titleI18n
    updatedAt
    userId
    
  }
}